[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/MattiaGaspa/asciinator"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/asciinator/:splat"
  status = 200
